export const CATEGORY_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const CATEGORY_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const CATEGORY_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const CATEGORY_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const CATEGORY_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const CATEGORY_CREATE_FAIL = "PRODUCT_CREATE_FAIL";
export const CATEGORY_CREATE_RESET = "PRODUCT_CREATE_RESET";

export const CATEGORY_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
export const CATEGORY_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const CATEGORY_UPDATE_FAIL = "PRODUCT_UPDATE_FAIL";
export const CATEGORY_UPDATE_RESET = "PRODUCT_UPDATE_RESET";

export const CATEGORY_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const CATEGORY_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const CATEGORY_DELETE_FAIL = "PRODUCT_DELETE_FAIL";
export const CATEGORY_DELETE_RESET = "PRODUCT_DELETE_RESET";
