const data = {
    products: [
      {
        _id: '1',
        name: 'Action Figure 01',
        category: 'Action Figure',
        image: '/template/images/actionfigure/kirito1.jpg',
        price: 1200000,
        countInStock: 10,
        rating: 4.5,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'Action Figure 02',
        category: 'Action Figure',
        image: '/template/images/actionfigure/shiro1.jpg',
        price: 1000000,
        countInStock: 20,
        rating: 4.0,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Action Figure 03',
        category: 'Action Figure',
        image: '/template/images/actionfigure/natsu1.jpg',
        price: 2200000,
        countInStock: 0,
        rating: 4.8,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Chibi Figure 01',
        category: 'Chibi Figure',
        image: '/template/images/chibifigure/aqua1.jpg',
        price: 780000,
        countInStock: 15,
        rating: 4.5,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Chibi Figure 02',
        category: 'Chibi Figure',
        image: '/template/images/chibifigure/sasuke1.jpg',
        price: 650000,
        countInStock: 5,
        rating: 4.5,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Chibi Figure 03',
        category: 'Chibi Figure',
        image: '/template/images/chibifigure/miku1.jpg',
        price: 1390000,
        countInStock: 12,
        rating: 4.5,
        description: 'high quality product',
      },
      {
        _id: '7',
        name: 'Manga 01',
        category: 'Manga',
        image: '/template/images/manga/m1.jpg',
        price: 1390000,
        countInStock: 6,
        rating: 4.5,
        description: 'high quality product',
      },
      {
        _id: '8',
        name: 'Manga 02',
        category: 'Manga',
        image: '/template/images/manga/m2.jpg',
        price: 139000,
        countInStock: 11,
        rating: 4.5,
        description: 'high quality product',
      },
      {
        _id: '9',
        name: 'Manga 03',
        category: 'Manga',
        image: '/template/images/manga/m3.jpg',
        price: 139000,
        countInStock: 9,
        rating: 4.5,
        description: 'high quality product',
      },
    ],
  };
  export default data;
  